// Code generated by protoc-gen-go.
// source: chaincode/chaincode_info.proto
// DO NOT EDIT!

/*
Package chaincode is a generated protocol buffer package.

It is generated from these files:
	chaincode/chaincode_info.proto

It has these top-level messages:
	ChaincodeInfo
*/
package chaincode

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type ChaincodeInfo struct {
	ParentChaincodeName string `protobuf:"bytes,1,opt,name=parentChaincodeName" json:"parentChaincodeName,omitempty"`
}

func (m *ChaincodeInfo) Reset()         { *m = ChaincodeInfo{} }
func (m *ChaincodeInfo) String() string { return proto.CompactTextString(m) }
func (*ChaincodeInfo) ProtoMessage()    {}
